"""change fname to filename

Revision ID: 5a87402fd130
Revises: 1e613592758a
Create Date: 2023-06-14 23:44:54.745071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a87402fd130'
down_revision = '1e613592758a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=50), nullable=True))
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
