"""Tạo UserRole

Revision ID: 6faaf29bb2ad
Revises: 5a87402fd130
Create Date: 2023-06-18 17:00:53.319974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faaf29bb2ad'
down_revision = '5a87402fd130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
